---

- name: Remove bootstrap config
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_KUBECONFIG_ARGS='
    line: "Environment=\"KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf\""
  notify:
    - reload kubelet
  become: yes

- name: Set extra kubeadm arguments
  template:
    owner: root
    group: root
    mode: 644
    src: kubelet.conf
    dest: /etc/sysconfig/kubelet
  become: yes

- name: Create empty kubelet config file
  template:
    owner: root
    group: root
    mode: 644
    src: kubelet-config.yaml
    dest: /var/lib/kubelet/config.yaml
  become: yes

- name: Enable Kubelet
  service:
    name: kubelet
    enabled: yes
  become: yes
