---

- name: Disable SELinux
  selinux:
    state: disabled
  become: yes

- name: Add Kubernetes Repo
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Install Kubeadm
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - kubeadm
    - kubelet
    - kubernetes-cni
  environment: "{{ kubeadm_proxy_env }}"
  become: yes

- name: Set cgroup driver
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_CGROUP_ARGS='
    line: "Environment=\"KUBELET_CGROUP_ARGS=--cgroup-driver={{ kubeadm_cgroup_driver }}\""
  notify:
    - reload kubelet
  become: yes

- name: Enable Kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
  become: yes
